name: uboat_course_calculator
description: The boat course calculator for torpedo data computer in Uboat game.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_picker: ^2.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: ^2.4.6

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'icon/ios.png'
  image_path_android: 'icon/android.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'icon/adaptive.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
